//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MondaySoccer.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Game_Player = new HashSet<Game_Player>();
        }
    
        public long GameID { get; set; }
        public System.DateTime Date { get; set; }
        public long HomeTeam { get; set; }
        public long AwayTeam { get; set; }
        public Nullable<int> HomeScore { get; set; }
        public Nullable<int> AwayScore { get; set; }
        public Nullable<long> MVP { get; set; }
        public string StateCod { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual ICollection<Game_Player> Game_Player { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
