//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MondaySoccer.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Player
    {
        public long InvitationPlayerID { get; set; }
        public long GameID { get; set; }
        public long PlayerID { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Golos { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsSubstitute { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
