//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MondaySoccer.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MondaySoccerEntities : DbContext
    {
        public MondaySoccerEntities()
            : base("name=MondaySoccerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Game> Game { get; set; }
        public DbSet<Game_Player> Game_Player { get; set; }
        public DbSet<Player> Player { get; set; }
        public DbSet<State> State { get; set; }
        public DbSet<Team> Team { get; set; }
    }
}
