//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MondaySoccer.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Game = new HashSet<Game>();
            this.Game1 = new HashSet<Game>();
            this.Player = new HashSet<Player>();
        }
    
        public long TeamID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Game> Game { get; set; }
        public virtual ICollection<Game> Game1 { get; set; }
        public virtual ICollection<Player> Player { get; set; }
    }
}
