CREATE TABLE [Player]
(
	[PlayerID] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [Nickname] NVARCHAR(250) NULL, 
    [TeamID] BIGINT NOT NULL, 
    CONSTRAINT [FK_Player_ToTeam] FOREIGN KEY (TeamID) REFERENCES Team(TeamID)
)
